### ISSUE TITLE
6th button repeating

### ISSUE THREAD

**Issue by RFC2795** [tlaukkanen/pikku-macropad#1]
Thank you for sharing this. I've built this now and it almost all works... except button 6 continually repeats.

I changed
for i in range(0,5):
    buttons[i].direction = digitalio.Direction.INPUT
    buttons[i].pull = digitalio.Pull.DOWN

to
for i in range(0,6):
    buttons[i].direction = digitalio.Direction.INPUT
    buttons[i].pull = digitalio.Pull.DOWN

and it works perfectly now.

**Comment by tlaukkanen** [comment]
@RFC2795 thanks! Somehow randomly it worked for me without that one but indeed I did get this myself yesterday on my device. Python's `range` was new to me and should have known that it does *not* include the stop digit to the range :)

Merged this fix to the code.
